### ISSUE TITLE
Blocket new UI broke the RSS bot

### ISSUE THREAD

**Issue by BoKKeR** [henrik/blocket_se_feeds#3]
I am pretty sure the new UI that went up today broke the RSS scraping

**Comment by henrik** [comment]
Hi,

Thank you for letting me know. I will most likely retire the service since I haven’t used it myself for many years and would rather not maintain it.

If anyone wants to set something similar up, whether it’s based on this code or not (if I did update it myself I’d rewrite most of it at this point), please feel free.

**Comment by henrik** [comment]
This service has now been "officially" retired.
